### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan#15]
Issue when taking slices close to the stump end point (self.vert[:,2].min())

Original author: Omar

**Comment by jack-parsons** [comment]
Generating measurements using invalid markers, as shown results in a crash
![image](https://user-images.githubusercontent.com/7894397/62222683-ac1ef400-b3ab-11e9-80a8-a861fd036a93.png)

**Comment by JoshuaSteer** [comment]
I'll fix that one

**Comment by JoshuaSteer** [comment]
Completely reworked the analyst code so it no longer auto-selects the tip, requires limits which can be normalised
