### ISSUE TITLE
ICP Failing with a coarse static mesh

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan#18]
Running ICP using a coarse static mesh (esp. a coarse static and moving mesh) caused attached SVD linear least squares non-convergence error. Try optimisation-based option?
![image](https://user-images.githubusercontent.com/7894397/61966970-0e52b000-afcc-11e9-9a02-cfbdaf99cf16.png)

Original Author: @alexd103

**Comment by JoshuaSteer** [comment]
In this case, use the idxPoints method to only sample some of the mesh #59
