### ISSUE TITLE
Trim Test

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan#22]
Check the max vertex is at the trimline i.e. none above

Original Author: @JoshuaSteer

**Comment by jack-parsons** [comment]
@JoshuaSteer I'm trying the test you described, however I'm not exactly sure how to use the method. Would you be able to tell me what `self.amp.planarTrim(10, plane=2)` would do for example. Thanks in advance :)

**Comment by JoshuaSteer** [comment]
## self.amp.planarTrim(t, plane=2)

## Check vert[:, 2].max < t

**Comment by jack-parsons** [comment]
I'm getting the max to be 10.0 when t=10 is passed in. Just want to check, is it "<="?

**Comment by JoshuaSteer** [comment]
Yep just testing you! ;)
