### ISSUE TITLE
Improve report generation

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan#26]
May want to consider generating report as HTML, or some other markup language instead of using PDF template (as we discussed) as PDF dependency is flaky.

**Comment by jack-parsons** [comment]
Just found out why it seemed to only work sometimes. There need to pick points on the object for the images to be generated otherwise it just crashes.

Still can't get PDF output to work unfortunately.

**Comment by JoshuaSteer** [comment]
That makes sense, at least we can quite easily add in a pop-up error to prevent it crashing. 

Ergh, I've had a look online and can't find a simple way to do it yet

**Comment by jack-parsons** [comment]
I've found a module called webbrowser (in the Python standard library) that can open files in the default web browser. I could use that to open the HTML file, and then run a script to bring up the print dialog. It's even supposed to be platform independent!

**Comment by JoshuaSteer** [comment]
Very nice! Especially as in Python standard library!

**Comment by jack-parsons** [comment]
@JoshuaSteer I've been experimenting with using HTML for the measurement report instead of the PDF, however, I've encountered a few issues that make it seem less attractive than I originally hoped.

1. When printing, there are headers and footers (as illustrated below) unless user disables it in print options. I have read that these can be removed using margins, but it might not work for all web browsers.
![image](https://user-images.githubusercontent.com/7894397/62214204-7e7e7e80-b39c-11e9-8edb-6b33853a7e10.png)

2. Images need to be exported with HTML, so need to bundle all images and css etc files into directory - which seems pretty messy.

3. Inserting the measurements into the boxes on the image cannot be done (cleanly) using just HTML.
![image](https://user-images.githubusercontent.com/7894397/62213779-99042800-b39b-11e9-910c-c7530329c9f6.png)

While I have been testing Omar's PDF stuff, I've actually got it working fairly consistently - PyPDF2 and reportlab seem to work with the versions currently in requirement.txt. There are still crashes, but most are to do with GUI issues rather than the PDF code.

Do you want me to continue with switching to HTML, or should I just clean up the existing code so it's more reliable and user-friendly?

**Comment by JoshuaSteer** [comment]
This is a classic 'feels like it should be easy, but isn't'. Good work to investigate though. 

If you have the pdf code working then merge that into master and work on fixing those GUI bugs so it doesn't crash. We'll keep thinking about alternative options for the report, maybe good to make a new branch so at least we can carry on looking at the master

**Comment by jack-parsons** [comment]
@JoshuaSteer the report generation is not working again - I believe it has something to do with the changed analyse module.
Traceback:
> <class 'tuple'>: (<class 'AttributeError'>, AttributeError("'AmpObject' object has no attribute 'MeasurementsOut'",), None) at line 388 in AmpScanGUI.py

I tried changing line 388 to ```output_file_path = analyse.MeasurementsOut(self.files[name], self.pnt)``` but this created another issue in analyse.py
> <class 'tuple'>: (<class 'AttributeError'>, AttributeError("'AmpObject' object has no attribute 'axis'",), None) at line 434 in analyse.py

To reproduce, open an stl file, select a pick point, and run "Generate Mesurements"

**Comment by JoshuaSteer** [comment]
Thanks for this, I'll have a look
