### ISSUE TITLE
Picking labels all the same

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan#29]
![image](https://user-images.githubusercontent.com/7894397/62143260-9942eb80-b2e7-11e9-87d5-8df29d7ed104.png)
All the picking labels are currently "mid patella". Is this correct?

**Comment by jack-parsons** [comment]
@abel-research/ampscan am I correct in saying that only the first pick point selected is used to identify where the "mid patella" is located - which is used as a reference to calculate the measurements of the scan for the report?

**Comment by JoshuaSteer** [comment]
Yep, that's right

**Comment by jack-parsons** [comment]
Would you like me to make it so the user can't put multiple pick points down (assuming the other points aren't being used for something else)?

**Comment by JoshuaSteer** [comment]
In the future we will probably add the ability to select new points, for the moment lets limit to one but add a comment in the code so it's clear how to revert back to multiple points for a future dev

**Comment by jack-parsons** [comment]
For now, I've made an error pop up when more points are added in commit 010eba1a23fdcc2c40ce86c530db0d32ac475a6c.
