### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan#3]
Simple shapes with known error
- [x] Two spheres with different radii
- [x] One sphere and one spheroid

Original Author: @JoshuaSteer

**Comment by jack-parsons** [comment]
@JoshuaSteer what would be the best values to compare to test that the output is what's expected for these tests? Is there a single value I can test, or would it be a matter of going through the AmpObject and compare all the point differences?

**Comment by JoshuaSteer** [comment]
We can easily calculate the radius and volume to compare

**Comment by jack-parsons** [comment]
Added check between spheroid and sphere in cd87de50b2988e986ca62605ff9ffd152196549d
